name: ci

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: yarn install
        run: yarn install
      - name: yarn build
        run: yarn build
        env:
          GITHUB_PAGES: true
